version: 1.0.0.{build}
branches:
  only:
  - master
environment:
build_script:
- ps: ./build/v1/build-win.ps1 -Target "RC" -Script ".\build\v1\build.cake" -Recipe "recipe.yml" --settings_skipverification=true
build: off
artifacts:
- path: ./dist/app-nodejs
  name: app-nodejs
notifications:
- provider: Email
  to:
  - nicolagmt@hotmail.com
  subject: angular-node-electron-seed - appveyor
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
